name: Test conflict commit push
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    name: Concurrent Job 1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Edit file
      run: |
        python3 editor.py

    - name: Commit and Push changes
      uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        email: test@gmail.com
        name: TestCommitPush
        commit_message: edit edit_me.txt
        target_branch: main
        remote_repository: https://github.com/bbompk/test_commit_push
        access_token: ${{ secrets.ACTIONS_AUTH_TOKEN }}
        force: 0
  
  job2:
    name: Concurrent Job 2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Edit file
      run: |
        python3 editor.py

    - name: Commit and Push changes
      uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        email: test@gmail.com
        name: TestCommitPush
        commit_message: edit edit_me.txt
        target_branch: main
        remote_repository: https://github.com/bbompk/test_commit_push
        access_token: ${{ secrets.ACTIONS_AUTH_TOKEN }}
        force: 0
